### PR TITLE
Correcting variable as it should be a list rather than string

### PR DESCRIPTION
**Pull request by wojukasz**
# Description

Following [usage](https://github.com/rubrikinc/terraform-aws-rubrik-cloud-cluster#usage) example TF plan fails with following errors:
```
Error: module.rubrik_aws_cloud_cluster.aws_instance.rubrik_cluster[0]: vpc_security_group_ids: should be a list
Error: module.rubrik_aws_cloud_cluster.aws_instance.rubrik_cluster[1]: vpc_security_group_ids: should be a list
Error: module.rubrik_aws_cloud_cluster.aws_instance.rubrik_cluster[2]: vpc_security_group_ids: should be a list
Error: module.rubrik_aws_cloud_cluster.aws_instance.rubrik_cluster[3]: vpc_security_group_ids: should be a list
```
This is due to missing brackets in https://github.com/rubrikinc/terraform-aws-rubrik-cloud-cluster/blob/master/main.tf#L45

## Motivation and Context

Trying to deploy rubrik cluster using Terraform 0.11.14

## How Has This Been Tested?
- I have deployed the cluster successfully with fix proposed in this PR using my fork.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by shamsway** [comment]
Thanks @wojukasz - this looks pretty straightforward but i'm not some place I can verify this change, so I will merge this after I can test.

Here is the related documentation for anyone who may be interested:  https://www.terraform.io/docs/providers/aws/r/instance.html#vpc_security_group_ids

**Comment by shamsway** [comment]
One other thing @wojukasz - will you update this to merge into the devel branch?

**Comment by wojukasz** [comment]
Thanks, I have changed base as requested @shamsway 
Are you happy for me to merge?

**Comment by shamsway** [comment]
@wojukasz, sorry for the delay getting back to you, I was out of the office for a few days. I took at look back at my usage of this module and I've taken the approach of defining `${var.aws_vpc_security_group_ids}` as a list (example below). The variable type is also defined as a list in `variables.tf`. When that is done, there is no need to make a change to `main.tf`. I asked @drew-russell to take a look as well so he can give his $0.02.

```
module "rubrik_aws_cloud_cluster" {
  source = "github.com/rubrikinc/use-case-terraform-module-for-aws-cloud-cluster"

  aws_vpc_security_group_ids = ["sg-a01234567"]
  aws_subnet_id              = "subnet-0123456789abcdef"
  cluster_name               = "rubrik-cloud-cluster"
  admin_email                = "admin@noreply.com"
  dns_search_domain          = ["rubrikdemo.com"]
  dns_name_servers           = ["8.8.8.8"]
  aws_disable_api_termination = false
  timeout		             = 300
}
```

**Comment by wojukasz** [comment]
thanks @shamsway  you are right, apologies for creating confusion and thanks for taking the time to have a look, closing the PR!

**Pull request closed without merging**
